msgbox "Este Archivo ha sido descargado de:"
msgbox "https://rx580-oficial.github.io/RX580.github.io/"
msgbox "Tù pagina de juegos favorita"
msgbox "Recuerda suscribirte a: www.youtube.com/@RX580Gaming"
msgbox "Disfruta tù Juego :D"